- name: Create kubernetes directory
  file:
    path: /opt/mental-health/kubernetes
    state: directory
    mode: '0755'

- name: Copy backend deployment YAML
  copy:
    src: "{{ playbook_dir }}/../kubernetes/backend-deployment.yml"
    dest: /opt/mental-health/kubernetes/backend-deployment.yml

- name: Copy backend service YAML
  copy:
    src: "{{ playbook_dir }}/../kubernetes/backend-service.yml"
    dest: /opt/mental-health/kubernetes/backend-service.yml

- name: Copy frontend deployment YAML
  copy:
    src: "{{ playbook_dir }}/../kubernetes/frontend-deployment.yml"
    dest: /opt/mental-health/kubernetes/frontend-deployment.yml

- name: Copy frontend service YAML
  copy:
    src: "{{ playbook_dir }}/../kubernetes/frontend-service.yml"
    dest: /opt/mental-health/kubernetes/frontend-service.yml
