---
- name: Ensure kubernetes directory exists
  file:
    path: "{{ deploy_path }}/kubernetes"
    state: directory
    mode: '0755'

- name: Copy backend deployment manifest
  copy:
    src: "{{ project_root }}/kubernetes/backend-deployment.yml"
    dest: "{{ deploy_path }}/kubernetes/backend-deployment.yml"
    remote_src: no

- name: Copy backend service manifest
  copy:
    src: "{{ project_root }}/kubernetes/backend-service.yml"
    dest: "{{ deploy_path }}/kubernetes/backend-service.yml"
    remote_src: no

- name: Copy frontend deployment manifest
  copy:
    src: "{{ project_root }}/kubernetes/frontend-deployment.yml"
    dest: "{{ deploy_path }}/kubernetes/frontend-deployment.yml"
    remote_src: no

- name: Copy frontend service manifest
  copy:
    src: "{{ project_root }}/kubernetes/frontend-service.yml"
    dest: "{{ deploy_path }}/kubernetes/frontend-service.yml"
    remote_src: no

- name: Copy ingress configuration
  copy:
    src: "{{ project_root }}/kubernetes/ingress.yml"
    dest: "{{ deploy_path }}/kubernetes/ingress.yml"
    remote_src: no

- name: Copy backend HPA configuration
  copy:
    src: "{{ project_root }}/kubernetes/backend-hpa.yml"
    dest: "{{ deploy_path }}/kubernetes/backend-hpa.yml"
    remote_src: no

- name: Copy frontend HPA configuration
  copy:
    src: "{{ project_root }}/kubernetes/frontend-hpa.yml"
    dest: "{{ deploy_path }}/kubernetes/frontend-hpa.yml"
    remote_src: no