---
app_name: mental-health
backend_port: 5001
frontend_port: 5003
project_root: "/home/tanvi/Desktop/MLOPS_MH"   # Still your Desktop for source files
deploy_path: "/opt/mental-health"              # Target path for deployment
backend_container_name: mental-health-backend
frontend_container_name: mental-health-frontend
docker_registry: tanvikulkarni33
backend_image: "{{ docker_registry }}/mental-health-backend:latest"
frontend_image: "{{ docker_registry }}/mental-health-frontend:latest"
