app_name: mental-health
backend_port: 5001
frontend_port: 5003
project_root: "/home/tanvi/Desktop/MLOPS_MH"
deploy_path: "/opt/mental-health"
backend_container_name: mental-health-backend
frontend_container_name: mental-health-frontend

# These will be fetched dynamically from Vault using Ansible's hashi_vault plugin
docker_registry: "{{ lookup('community.hashivault.hashivault', 'secret=kv/mental-health/docker#username') }}"
backend_image: "{{ docker_registry }}/mental-health-backend:latest"
frontend_image: "{{ docker_registry }}/mental-health-frontend:latest"
