apiVersion: apps/v1
kind: Deployment
metadata:
  name: mental-health-backend-deployment
  labels:
    app: mental-health-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mental-health-backend
  template:
    metadata:
      labels:
        app: mental-health-backend
    spec:
      containers:
      - name: backend
        image: tanvikulkarni33/mental-health-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"

# readinessProbe:
#   httpGet:
#     path: /health
#     port: 5001
#   initialDelaySeconds: 5
#   periodSeconds: 10

# livenessProbe:
#   httpGet:
#     path: /health
#     port: 5001
#   initialDelaySeconds: 15
#   periodSeconds: 20
