---
- name: Deploy Mental Health Application
  hosts: localhost
  connection: local
  become: yes

  vars:
    project_root: "/var/lib/jenkins/workspace/MentalHealthRiskPrediction"
    deploy_path: "/opt/mental-health"
    app_name: "mental-health"
    backend_port: 5001
    frontend_port: 5003
    kubeconfig_path: "/var/lib/jenkins/.kube/config"

  tasks:
    - name: Ensure Jenkins kubeconfig exists
      stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_status

    - name: Fail if kubeconfig is missing
      fail:
        msg: "Jenkins kubeconfig not found at {{ kubeconfig_path }}"
      when: not kubeconfig_status.stat.exists

    - name: Set kubectl environment for Jenkins
      set_fact:
        kubectl_env:
          KUBECONFIG: "{{ kubeconfig_path }}"

  roles:
    - backend
    - frontend
    - copy_k8files
    - k8s_deploy

- name: Verify Services and Deploy HPAs
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Wait for backend service to become healthy
      uri:
        url: "http://localhost:{{ backend_port }}/health"
        return_content: yes
      register: health_check
      until: health_check.status == 200
      retries: 10
      delay: 5
      ignore_errors: yes

    - name: Show backend health check response
      debug:
        var: health_check.content

    - name: Deploy Backend HPA
      command: >
        kubectl apply -f {{ deploy_path }}/kubernetes/backend-hpa.yml
        --kubeconfig={{ kubeconfig_path }}
      environment: "{{ kubectl_env }}"
      become_user: jenkins

    - name: Deploy Frontend HPA
      command: >
        kubectl apply -f {{ deploy_path }}/kubernetes/frontend-hpa.yml
        --kubeconfig={{ kubeconfig_path }}
      environment: "{{ kubectl_env }}"
      become_user: jenkins

    - name: Verify HPAs
      command: kubectl get hpa
      register: hpa_status
      changed_when: false
      
    - name: Display HPA status
      debug:
        var: hpa_status.stdout_lines