---
- name: Deploy Mental Health Application
  hosts: localhost
  connection: local
  become: yes

  vars:
    # Dynamic project root detection
    is_jenkins: "{{ lookup('env', 'JENKINS_HOME') is defined }}"
    project_root: >-
      {{
        '/var/lib/jenkins/workspace/MentalHealthRiskPrediction' if is_jenkins
        else '/home/tanvi/Desktop/MLOPS_MH/MLOpsSPE_MentalHealthRIskPrediction-main'
      }}
    project_root: "/home/tanvi/Desktop/MLOPS_MH/MLOpsSPE_MentalHealthRIskPrediction-main"
    deploy_path: "/opt/mental-health"
    k8s_dir: "{{ project_root }}/kubernetes"  # Explicit kubernetes directory path
    app_name: "mental-health"
    kubeconfig_path: "{{ '~/.kube/config' if not is_jenkins else '/var/lib/jenkins/.kube/config' }}"

    # Container ports
    backend_port: 5001
    frontend_port: 5003

    # Vault secret lookups
    vault_docker_username: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/mental-health/docker:username') }}"
    vault_docker_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/mental-health/docker:password') }}"

  roles:
    - backend
    - frontend
    - copy_k8files
    - k8s_deploy

- name: Verify Services
  hosts: localhost
  connection: local
  tasks:
    - name: Wait for backend service to become healthy
      uri:
        url: "http://localhost:{{ backend_port }}/health"
        return_content: yes
      register: health_check
      until: health_check.status == 200
      retries: 10
      delay: 5
      ignore_errors: yes

    - name: Show health check response
      debug:
        var: health_check.content