---
- name: Deploy Mental Health Application
  hosts: localhost
  connection: local
  become: yes

  vars:
    project_root: "/home/tanvi/Desktop/MLOPS_MH"
    deploy_path: "/opt/mental-health"
    app_name: "mental-health"
    kubeconfig_path: "/var/lib/jenkins/.kube/config"
    playbook_dir: "{{ playbook_dir }}"

    # Vault secret lookups
    vault_docker_username: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/mental-health/docker:username') }}"
    vault_docker_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/mental-health/docker:password') }}"

  roles:
    - backend
    - frontend
    - copy_k8files
    - k8s_deploy

- name: Verify Services
  hosts: localhost
  connection: local
  tasks:
    - name: Wait for backend service to become healthy
      uri:
        url: http://localhost:{{ backend_port }}/health
        return_content: yes
      register: health_check
      until: health_check.status == 200
      retries: 10
      delay: 5
      ignore_errors: yes

    - name: Show health check response
      debug:
        var: health_check.content
